version: '3.8'  

services:  
  backend:  
    build: .   
    volumes:  
      - ./src:/app  
    ports:  
      - "8080:8080"   
    command: uvicorn controller.memo:app  --port 8080 --reload  
    environment:  
      MYSQL_HOST: db  
      MYSQL_USER: root  
      MYSQL_PASSWORD: 123456  
      MYSQL_DATABASE: anzhai_memo  
    depends_on:  
      - db  

  db:  
    image: mysql:latest  
    restart: always  
    environment:  
      MYSQL_ROOT_PASSWORD: 123456  
      MYSQL_DATABASE: anzhai_memo  
    volumes:  
      - dbdata:/var/lib/mysql  

volumes:  
  dbdata: